WIDGET_REGISTRY = [
    {"id": "clock", "name": "Clock", "icon": "clock", "category": "core", "default_visible": True},
    {"id": "date", "name": "Date", "icon": "calendar", "category": "core", "default_visible": True},
    {"id": "system_monitor", "name": "System Monitor", "icon": "cpu", "category": "system", "default_visible": True},
    {"id": "processes", "name": "Running Processes", "icon": "list", "category": "system", "default_visible": True},
    {"id": "tasks", "name": "Tasks", "icon": "check-square", "category": "productivity", "default_visible": True},
    {"id": "notes", "name": "Notes", "icon": "edit-3", "category": "productivity", "default_visible": True},
    {"id": "projects", "name": "Project Manager", "icon": "folder", "category": "devops", "default_visible": True},
    {"id": "windows_control", "name": "Windows Control", "icon": "power", "category": "system", "default_visible": True},
    {"id": "notifications", "name": "Notifications", "icon": "bell", "category": "core", "default_visible": False},
    {"id": "quotes", "name": "Quotes", "icon": "message-circle", "category": "extra", "default_visible": True},
    {"id": "prayer_times", "name": "Prayer Times", "icon": "sunrise", "category": "extra", "default_visible": True},
    {"id": "azkar", "name": "Azkar", "icon": "book-open", "category": "extra", "default_visible": True},
    {"id": "stopwatch", "name": "Stopwatch", "icon": "watch", "category": "productivity", "default_visible": True},
    {"id": "countdown", "name": "Countdown", "icon": "target", "category": "productivity", "default_visible": True},
    {"id": "calendar", "name": "Calendar", "icon": "calendar", "category": "productivity", "default_visible": True},
    {"id": "file_manager", "name": "File Manager", "icon": "hard-drive", "category": "devops", "default_visible": True},
    {"id": "app_health", "name": "App Health / Watchdog", "icon": "activity", "category": "system", "default_visible": True},
]
